version: "3.9"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        container_name: flask_app
    container_name: flask_app
    environment:
      - CONTAINER_NAME=flask_app
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    working_dir: /flask_app
    volumes:
      - .:/flask_app
    restart: always
    ports:
      - "5009:5000"
    command: ["flask", "run", "--reload"]
